version: '3'  # You can specify the Compose version here

services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: project22
      MYSQL_USER: srikanth
      MYSQL_PASSWORD: srikanth123

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: srikanth123
      WORDPRESS_DB_USER: srikanth
      WORDPRESS_DB_NAME: project22
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
  db_data:

